version: '2'
services:
  postgres-local:
    image: postgres:13.15-bookworm
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_pass
      POSTGRES_DB: microservices-delivery
    ports:
      - 5432:5432
    networks:
      - kafka-network
    restart: unless-stopped
    # https://stackoverflow.com/questions/62697071/docker-compose-postgres-upgrade-initdb-error-directory-var-lib-postgresql-da
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
  
  kafka-broker:
    image: confluentinc/cp-kafka:7.4.5
    networks:
      - kafka-network
    ports:
      - 29092:29092
    env_file:
      - broker.env

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.5
    hostname: schema-registry
    depends_on:
      - kafka-broker
    networks:
      - kafka-network
    ports:
      - 8081:8081
    env_file:
      - registry.env

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.5
    depends_on:
      - kafka-broker
      - schema-registry
      - postgres-local
    networks:
      - kafka-network
    ports:
      - 8093:8093
    links:
      - postgres-local
    volumes:
      - "./kafka-connect/plugins:/etc/kafka/connect/plugins"
      - "./scripts/build-connectors.sh:/etc/kafka/scripts/build-connectors.sh"
    env_file:
      - connect.env
    command:
      - /etc/kafka/scripts/build-connectors.sh
        
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:53a6553765a806eda9905c43bfcfe09da6812035
    depends_on:
      - kafka-broker
      - schema-registry
      - kafka-connect
    networks:
      - kafka-network
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'false'
      SPRING_CONFIG_ADDITIONAL-LOCATION: /etc/kafka/kafka-ui/config.yml 
    volumes:
      - ./kafka-ui/config.yml:/etc/kafka/kafka-ui/config.yml

networks:
  kafka-network: